apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    track: canary
  name: helloworld-canary
spec:
  ports:
    - nodePort: 30001
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: helloworld
    track: canary
  type: LoadBalancer
