apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: helloworld
  type: LoadBalancer
